# -*- coding: utf-8 -*-
"""BehindThePipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j-sB9qD6Bl4wKYDEpJcmQXfNUkpo5zZR
"""

import transformers

"""## Tokenizer"""

tokenizer=transformers.AutoTokenizer.from_pretrained("bert-base-uncased")
raw_input=["This is tea","Hello rida","Hello"]
input=tokenizer(raw_input,padding=True,truncation=True,return_tensors="pt")

print(input)

"""## Model"""

model=transformers.AutoModel.from_pretrained("bert-base-uncased")
output=model(**input)
print(output)

"""## Post Processing"""

import torch
predictions = torch.nn.functional.softmax(output.logits, dim=-1)
print(predictions)