# -*- coding: utf-8 -*-
"""Pipelines.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NlaoP3lbYYoBKzco5YAogqjKhOhSC35Z
"""

!pip install transformers

from transformers import pipeline



from transformers import pipeline

classifier = pipeline("sentiment-analysis")
classifier("I've been waiting for a HuggingFace course my whole life.")

classifier(
    ["I've been waiting for a HuggingFace course my whole life.", "I hate this so much!"]
)

classifier = pipeline("zero-shot-classification")
classifier(
    "This is a course about the Transformers library",
    candidate_labels=["education", "politics", "business"],
)

classifier("Imran khan is in jail right now",
           candidate_labels=["education","politics","fashion"],)

from transformers import pipeline

generator = pipeline("text-generation")
generator("In this course, we will teach you how to",
          num_return_sequences=2, max_length=15,)

